before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: ./install-dependencies.sh
language: node_js
node_js:
  - "0.10"
  # whitelist
branches:
  only:
    - tam
script: tests/node_modules/karma/bin/karma start tests/karma.conf.js --single-run
