before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: ./install-dependencies.sh
language: node_js
node_js:
  - "0.10"
script: cd tests && node_modules/grunt-cli/bin/grunt --force -v

