before_install
  - cd tests/node_modules
  - npm install hackify-server
  - bower install hackify-server
install:
  - cd .. && cd .. && npm install tests
  - npm install recipal-server
language: node_js
node_js:
  - "0.10"
  # whitelist
branches:
  only:
    - tam
script: karma start tests/karma.conf.js
