install:
  - npm install tests
  - npm install tests/hackify-server
  - bower install tests/hackify-server
  - npm install recipal-server
language: node_js
node_js:
  - "0.10"
  # whitelist
branches:
  only:
    - tam
script: karma start tests/karma.conf.js
